version: "3.8"

services:

  dash:
    build: .
    container_name: dash
    depends_on:
      - postgres
    ports:
      - "8050:8050"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

  postgres:
    image: postgres:14.0-bullseye
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}/postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
